### ISSUE TITLE
adapt to upcoming `notify` api (M2)

### ISSUE THREAD

**Issue by r10s** [DeltaZen/chess#9]
notify the other player about 

- when an opponent joins
- when a move is made

observers should not be notified.

this requires a core with https://github.com/deltachat/deltachat-core-rust/pull/6230 checked out or merged

**Comment by adbenitez** [comment]
There is a problem I see here.... the notify API requires the notification message to be set in `update.info` which is not wanted/used in this game, since otherwise the chat will be spammed with "foo it is your turn" on every move, that is why this app was using the app summary for the notification of which user is the turn, so the notify API would need to use summary if info is not set or rather better have a dedicated notification text field, which would be the ideal because that way you can have custom message for user Foo that only Foo see in the UI

**Comment by r10s** [comment]
i am sceptical in having different messages etc. for different users, this might be somehow confusing as well - but we can always improve, not saying we cannot have sth like that at some point, but currently i do not think, it is needed and we should keep simple.

for the issue at hand, it is probably fine to just do the collapsing as usual (so that for most user only the last message is shown), and only for the notified user avoid the collapsing

**Comment by r10s** [comment]
> this requires a core with https://github.com/deltachat/deltachat-core-rust/pull/6230 checked out or merged

plus, this requires the UI to use the new self_addr api

**Comment by adbenitez** [comment]
> for the issue at hand, it is probably fine to just do the collapsing as usual (so that for most user only the last message is shown), and only for the notified user avoid the collapsing

I think there is a misconception of how collapsing works, it is useless in a turn-based game where different people will be sending the notification each time, plus even if it collapsed to older notifications from self it would just be super weird and useless info messages with the most recent notification being merged with an older info-message, anyways just to be sure it works as I said I tested it:

![image](https://github.com/user-attachments/assets/aa5234ce-a5f7-4ff4-9e46-287ef5f24079)
